# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82736d10f80a9973926e5ef465d1f942826a14418dfa2248c60a3e3d9d8d5f11fe8e8f4fa980ca186dfbf041c6b4d572a1fdc118a5191b16f63cf01f9eafdb16

test:
  secret_key_base: 84cdf652e53d5fefc9ab1f5bb1fd6228a7128d0c2fed136f294327f06e0a46e480feb5452b969e1f8966649e1715f3f3b357bb3b0650697dce1a9d1d57bc83b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
